services:
  nginx:
    image: nginx:latest
    container_name: nginx
    stop_signal: SIGINT
    volumes:
      - ./images/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./build/php/src:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - php

  php:
    build:
      context: ./build/php
      dockerfile: Dockerfile
    container_name: php
    stop_signal: SIGINT
    volumes:
      - ./src/:/usr/share/nginx/html
      - data:/data
    ports:
      - "9000:9000"

volumes:
  data: